replicaCount: 2

image:
  repository: hemanthgangula/crud-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  name: crud-app
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: crud-app.local
      paths: ["/"]

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

serviceAccount:
  create: true
  name: ""
